from __future__ import annotations

import argparse

from DyMaskRefactor.support_line.registry import SUPPORT_VARIANTS


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Run modularized source-anchored support experiments.")
    parser.add_argument("--config-json", default=None, help="Optional JSON config file. Keys use the same dest names as CLI args.")
    parser.add_argument("--variant", choices=sorted(SUPPORT_VARIANTS.keys()), default="baseline")
    parser.add_argument("--parquet-path", default="assets/data/train-00000-of-00262-57cebf95b4a9170c.parquet")
    parser.add_argument("--piebench-path", default=None)
    parser.add_argument("--sample-json", default=None)
    parser.add_argument("--output-root", default=None)
    parser.add_argument("--sample-count", type=int, default=8)
    parser.add_argument("--sample-seed", type=int, default=42)
    parser.add_argument("--row-indices", nargs="+", type=int, default=None)
    parser.add_argument("--run-limit", type=int, default=None)
    parser.add_argument("--model-id", default="runwayml/stable-diffusion-v1-5", help="HF model id or local Stable Diffusion directory.")
    parser.add_argument("--clip-model-id", default="openai/clip-vit-large-patch14", help="HF model id or local CLIP directory for metrics.")
    parser.add_argument("--ntip2p-root", default=None, help="Optional path to NTIP2P root. Defaults to DyMaskRefactor/third_party/NTIP2P if vendored.")
    parser.add_argument("--inversion-backend", choices=["ddim", "nti"], default="ddim")
    parser.add_argument("--image-size", type=int, default=512)
    parser.add_argument("--num-ddim-steps", type=int, default=10)
    parser.add_argument("--num-inversion-steps", type=int, default=None)
    parser.add_argument("--num-edit-steps", type=int, default=None)
    parser.add_argument("--guidance-scale", type=float, default=7.5)
    parser.add_argument("--nti-num-inner-steps", type=int, default=10)
    parser.add_argument("--nti-early-stop-epsilon", type=float, default=1e-5)
    parser.add_argument("--device", default="cuda")
    parser.add_argument("--dtype", default="float16")
    parser.add_argument("--sample-batch-size", type=int, default=1)
    parser.add_argument("--min-sample-batch-size", type=int, default=1)
    parser.add_argument("--disable-auto-batch-fallback", action="store_true")
    parser.add_argument("--disable-batch-warmup-probe", action="store_true")
    parser.add_argument("--enable-tf32", action="store_true")
    parser.add_argument("--channels-last", action="store_true")
    parser.add_argument("--enable-xformers", action="store_true")
    parser.add_argument("--keep-cuda-cache", action="store_true")
    parser.add_argument("--disable-attention-slicing", action="store_true")
    parser.add_argument("--disable-vae-slicing", action="store_true")
    parser.add_argument("--allow-download", action="store_true")
    parser.add_argument("--disable-structure-distance", action="store_true")
    parser.add_argument("--dino-model-name", default="dino_vitb8")
    parser.add_argument("--dino-weights-path", default=None, help="Optional local DINO checkpoint path used by structure distance.")
    parser.add_argument("--dino-global-patch-size", type=int, default=224)
    parser.add_argument("--skip-metrics", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--methods", nargs="+", default=["full_dynamic_mask"])
    parser.add_argument("--mask-mode", choices=["dynamic", "static"], default="dynamic")
    parser.add_argument("--global-blend-alpha", type=float, default=0.45)
    parser.add_argument("--global-blend-alphas", nargs="+", type=float, default=[0.3, 0.5, 0.7])
    parser.add_argument("--selected-step-count", type=int, default=5)
    parser.add_argument("--selected-step-stride", type=int, default=None)
    parser.add_argument("--save-inversion-tensors", action="store_true")
    parser.add_argument("--num-maps-per-mask", type=int, default=10)
    parser.add_argument("--mask-encode-strength", type=float, default=0.5)
    parser.add_argument("--mask-thresholding-ratio", type=float, default=3.0)
    parser.add_argument("--inpaint-strength", type=float, default=1.0)
    parser.add_argument("--support-rho", type=float, default=0.70)
    parser.add_argument("--soft-roi-start-weight", type=float, default=0.75)
    parser.add_argument("--soft-roi-end-weight", type=float, default=0.10)
    parser.add_argument("--anchor-hardness-start", type=float, default=0.35)
    parser.add_argument("--anchor-hardness-end", type=float, default=1.0)
    parser.add_argument("--support-soft-roi-blend", type=float, default=0.50)
    parser.add_argument("--anchor-enable-start-ratio", type=float, default=0.20)
    parser.add_argument("--anchor-enable-full-ratio", type=float, default=0.50)
    parser.add_argument("--support-soft-enable-start-ratio", type=float, default=0.25)
    parser.add_argument("--support-soft-enable-full-ratio", type=float, default=0.60)
    parser.add_argument("--support-floor-start-ratio", type=float, default=0.45)
    parser.add_argument("--support-floor-full-ratio", type=float, default=0.80)
    parser.add_argument("--support-floor-max", type=float, default=0.20)
    parser.add_argument("--anchor-relax-start-strength", type=float, default=0.35)
    parser.add_argument("--anchor-relax-end-strength", type=float, default=0.05)
    parser.add_argument("--consistency-floor", type=float, default=0.20)
    parser.add_argument("--roi-trust-max-strength", type=float, default=0.60)
    parser.add_argument("--roi-trust-start-ratio", type=float, default=0.45)
    parser.add_argument("--roi-trust-full-ratio", type=float, default=0.80)
    parser.add_argument("--soft-boundary-start-weight", type=float, default=0.18)
    parser.add_argument("--soft-boundary-end-weight", type=float, default=0.04)
    parser.add_argument("--core-read-start-weight", type=float, default=0.45)
    parser.add_argument("--core-read-end-weight", type=float, default=0.08)
    parser.add_argument("--boundary-read-start-weight", type=float, default=0.20)
    parser.add_argument("--boundary-read-end-weight", type=float, default=0.04)
    parser.add_argument("--boundary-anchor-start-weight", type=float, default=0.18)
    parser.add_argument("--boundary-anchor-end-weight", type=float, default=0.04)
    parser.add_argument("--boundary-confidence-weight", type=float, default=0.30)
    parser.add_argument("--roi-core-quantile", type=float, default=0.80)
    parser.add_argument("--roi-core-peak-ratio", type=float, default=0.60)
    parser.add_argument("--roi-core-threshold-min", type=float, default=0.15)
    parser.add_argument("--roi-core-threshold-max", type=float, default=0.50)
    parser.add_argument("--roi-core-min-active-ratio", type=float, default=0.05)
    parser.add_argument("--roi-core-active-floor", type=float, default=0.05)
    parser.add_argument("--roi-seed-offset", type=int, default=0)
    parser.add_argument("--roi-cache-root", default="runs/diffedit_roi_cache/source_prompt_c5h2")
    parser.add_argument("--underedit-support-gain", type=float, default=0.45)
    parser.add_argument("--underedit-mask-gain", type=float, default=0.20)
    parser.add_argument("--underedit-anchor-gain", type=float, default=0.30)
    parser.add_argument("--underedit-eps", type=float, default=1e-6)
    parser.add_argument("--underedit-temporal-rho", type=float, default=0.55)
    parser.add_argument("--log-path", default="log_support_refactor.md")
    return parser
