from __future__ import annotations

from DyMaskRefactor.support_line.specs import SupportVariantSpec


_BASE_MODULE = "DyMaskRefactor.support_line.base"
_PROGRESSIVE_MODULE = "DyMaskRefactor.support_line.variants_progressive"
_CONFIDENCE_MODULE = "DyMaskRefactor.support_line.variants_confidence"
_MAINLINE_MODULE = "DyMaskRefactor.support_line.variants_mainline"


SUPPORT_VARIANTS: dict[str, SupportVariantSpec] = {
    'baseline': SupportVariantSpec(
        key='baseline',
        display_name='Support Baseline',
        editor_ref=f'{_BASE_MODULE}:RefactorSupportBaselineEditor',
        variant_name='source_prompt_source_anchored_support_adaptive_v1',
        description='Adaptive temporal support blended with soft ROI and scheduled source anchoring.',
        run_prefix='support_baseline',
        default_output_root='scratch_source_anchor_refactor/support_baseline',
    ),
    'c1': SupportVariantSpec(
        key='c1',
        display_name='Support C1',
        editor_ref=f'{_PROGRESSIVE_MODULE}:RefactorSupportC1Editor',
        variant_name='source_prompt_source_anchored_support_c1_soft_memory_v1',
        description='Adds soft-aware support memory on top of the baseline support line.',
        run_prefix='support_c1',
        default_output_root='scratch_source_anchor_refactor/support_c1',
        extra_arg_names=('support_soft_roi_blend',),
    ),
    'c2': SupportVariantSpec(
        key='c2',
        display_name='Support C2',
        editor_ref=f'{_PROGRESSIVE_MODULE}:RefactorSupportC2Editor',
        variant_name='source_prompt_source_anchored_support_c2_delayed_anchor_v1',
        description='Adds delayed source anchoring on top of the C1-style branch.',
        run_prefix='support_c2',
        default_output_root='scratch_source_anchor_refactor/support_c2',
        extra_arg_names=(
            'support_soft_roi_blend',
            'anchor_enable_start_ratio',
            'anchor_enable_full_ratio',
        ),
    ),
    'c3': SupportVariantSpec(
        key='c3',
        display_name='Support C3',
        editor_ref=f'{_PROGRESSIVE_MODULE}:RefactorSupportC3Editor',
        variant_name='source_prompt_source_anchored_support_c3_delayed_anchor_delayed_soft_support_v1',
        description='Delays both anchor enablement and soft support memory blending.',
        run_prefix='support_c3',
        default_output_root='scratch_source_anchor_refactor/support_c3',
        extra_arg_names=(
            'support_soft_roi_blend',
            'anchor_enable_start_ratio',
            'anchor_enable_full_ratio',
            'support_soft_enable_start_ratio',
            'support_soft_enable_full_ratio',
        ),
    ),
    'c4': SupportVariantSpec(
        key='c4',
        display_name='Support C4',
        editor_ref=f'{_PROGRESSIVE_MODULE}:RefactorSupportC4Editor',
        variant_name='source_prompt_source_anchored_support_c4_late_roi_floor_v1',
        description='Adds a late support floor to keep weak edit drive from collapsing.',
        run_prefix='support_c4',
        default_output_root='scratch_source_anchor_refactor/support_c4',
        extra_arg_names=(
            'support_soft_roi_blend',
            'anchor_enable_start_ratio',
            'anchor_enable_full_ratio',
            'support_soft_enable_start_ratio',
            'support_soft_enable_full_ratio',
            'support_floor_start_ratio',
            'support_floor_full_ratio',
            'support_floor_max',
        ),
    ),
    'c5': SupportVariantSpec(
        key='c5',
        display_name='Support C5',
        editor_ref=f'{_CONFIDENCE_MODULE}:RefactorSupportC5Editor',
        variant_name='source_prompt_source_anchored_support_c5_confidence_local_anchor_v1',
        description='Keeps baseline support memory and relaxes source anchoring only where confidence is high.',
        run_prefix='support_c5',
        default_output_root='scratch_source_anchor_refactor/support_c5',
        extra_arg_names=(
            'anchor_relax_start_strength',
            'anchor_relax_end_strength',
        ),
    ),
    'c5h0': SupportVariantSpec(
        key='c5h0',
        display_name='Support C5H0',
        editor_ref=f'{_MAINLINE_MODULE}:RefactorSupportC5H0Editor',
        variant_name='source_prompt_source_anchored_support_c5h0_hard_core_v1',
        description='Latest-mainline branch start: hard-core support and hard-core confidence anchor relaxation.',
        run_prefix='support_c5h0',
        default_output_root='scratch_source_anchor_refactor/support_c5h0',
        extra_arg_names=(
            'anchor_relax_start_strength',
            'anchor_relax_end_strength',
        ),
    ),
    'c5h1': SupportVariantSpec(
        key='c5h1',
        display_name='Support C5H1',
        editor_ref=f'{_MAINLINE_MODULE}:RefactorSupportC5H1Editor',
        variant_name='source_prompt_source_anchored_support_c5h1_hard_core_soft_boundary_v1',
        description='Adds a thin soft boundary around the hard core while keeping support writes hard-core.',
        run_prefix='support_c5h1',
        default_output_root='scratch_source_anchor_refactor/support_c5h1',
        extra_arg_names=(
            'anchor_relax_start_strength',
            'anchor_relax_end_strength',
            'soft_boundary_start_weight',
            'soft_boundary_end_weight',
        ),
    ),
    'c5h2': SupportVariantSpec(
        key='c5h2',
        display_name='Support C5H2',
        editor_ref=f'{_MAINLINE_MODULE}:RefactorSupportC5H2Editor',
        variant_name='source_prompt_source_anchored_support_c5h2_deterministic_core_boundary_v1',
        description='Makes DiffEdit ROI deterministic per sample and splits it into a hard core plus normalized boundary.',
        run_prefix='support_c5h2',
        default_output_root='scratch_source_anchor_refactor/support_c5h2',
        extra_arg_names=(
            'anchor_relax_start_strength',
            'anchor_relax_end_strength',
            'core_read_start_weight',
            'core_read_end_weight',
            'boundary_read_start_weight',
            'boundary_read_end_weight',
            'boundary_anchor_start_weight',
            'boundary_anchor_end_weight',
            'boundary_confidence_weight',
            'roi_core_quantile',
            'roi_core_peak_ratio',
            'roi_core_threshold_min',
            'roi_core_threshold_max',
            'roi_core_min_active_ratio',
            'roi_core_active_floor',
            'roi_seed_offset',
            'roi_cache_root',
        ),
    ),
    'c5h3': SupportVariantSpec(
        key='c5h3',
        display_name='Support C5H3',
        editor_ref=f'{_MAINLINE_MODULE}:RefactorSupportC5H3Editor',
        variant_name='source_prompt_source_anchored_support_c5h3_underedit_rescue_v1',
        description='Adds an under-edit rescue branch on top of the deterministic core-boundary mainline.',
        run_prefix='support_c5h3',
        default_output_root='scratch_source_anchor_refactor/support_c5h3',
        extra_arg_names=(
            'anchor_relax_start_strength',
            'anchor_relax_end_strength',
            'core_read_start_weight',
            'core_read_end_weight',
            'boundary_read_start_weight',
            'boundary_read_end_weight',
            'boundary_anchor_start_weight',
            'boundary_anchor_end_weight',
            'boundary_confidence_weight',
            'roi_core_quantile',
            'roi_core_peak_ratio',
            'roi_core_threshold_min',
            'roi_core_threshold_max',
            'roi_core_min_active_ratio',
            'roi_core_active_floor',
            'roi_seed_offset',
            'roi_cache_root',
            'underedit_support_gain',
            'underedit_mask_gain',
            'underedit_anchor_gain',
            'underedit_eps',
        ),
    ),
    'c5h4': SupportVariantSpec(
        key='c5h4',
        display_name='Support C5H4',
        editor_ref=f'{_MAINLINE_MODULE}:RefactorSupportC5H4Editor',
        variant_name='source_prompt_source_anchored_support_c5h4_temporal_underedit_guard_v1',
        description='Current latest mainline: deterministic core-boundary editing plus temporal under-edit guard.',
        run_prefix='support_c5h4',
        default_output_root='scratch_source_anchor_refactor/support_c5h4',
        extra_arg_names=(
            'anchor_relax_start_strength',
            'anchor_relax_end_strength',
            'core_read_start_weight',
            'core_read_end_weight',
            'boundary_read_start_weight',
            'boundary_read_end_weight',
            'boundary_anchor_start_weight',
            'boundary_anchor_end_weight',
            'boundary_confidence_weight',
            'roi_core_quantile',
            'roi_core_peak_ratio',
            'roi_core_threshold_min',
            'roi_core_threshold_max',
            'roi_core_min_active_ratio',
            'roi_core_active_floor',
            'roi_seed_offset',
            'roi_cache_root',
            'underedit_support_gain',
            'underedit_mask_gain',
            'underedit_anchor_gain',
            'underedit_eps',
            'underedit_temporal_rho',
        ),
    ),
    'c6': SupportVariantSpec(
        key='c6',
        display_name='Support C6',
        editor_ref=f'{_CONFIDENCE_MODULE}:RefactorSupportC6Editor',
        variant_name='source_prompt_source_anchored_support_c6_confidence_roi_trust_v1',
        description='Keeps C5 local anchor relaxation and adds a late ROI-trust fallback plus a consistency floor.',
        run_prefix='support_c6',
        default_output_root='scratch_source_anchor_refactor/support_c6',
        extra_arg_names=(
            'anchor_relax_start_strength',
            'anchor_relax_end_strength',
            'consistency_floor',
            'roi_trust_max_strength',
            'roi_trust_start_ratio',
            'roi_trust_full_ratio',
        ),
    ),
    'c6b': SupportVariantSpec(
        key='c6b',
        display_name='Support C6b',
        editor_ref=f'{_CONFIDENCE_MODULE}:RefactorSupportC6BEditor',
        variant_name='source_prompt_source_anchored_support_c6b_confidence_roi_agreement_v1',
        description='Keeps C6 late roi-trust fallback but tightens it to support-mask agreement regions.',
        run_prefix='support_c6b',
        default_output_root='scratch_source_anchor_refactor/support_c6b',
        extra_arg_names=(
            'anchor_relax_start_strength',
            'anchor_relax_end_strength',
            'consistency_floor',
            'roi_trust_max_strength',
            'roi_trust_start_ratio',
            'roi_trust_full_ratio',
        ),
    ),
    'c6c': SupportVariantSpec(
        key='c6c',
        display_name='Support C6c',
        editor_ref=f'{_CONFIDENCE_MODULE}:RefactorSupportC6CEditor',
        variant_name='source_prompt_source_anchored_support_c6c_support_gap_recovery_v1',
        description='Keeps C6 late scheduling but converts the late branch into support-gap recovery for under-edited holes.',
        run_prefix='support_c6c',
        default_output_root='scratch_source_anchor_refactor/support_c6c',
        extra_arg_names=(
            'anchor_relax_start_strength',
            'anchor_relax_end_strength',
            'consistency_floor',
            'roi_trust_max_strength',
            'roi_trust_start_ratio',
            'roi_trust_full_ratio',
        ),
    ),
    'c6d': SupportVariantSpec(
        key='c6d',
        display_name='Support C6d',
        editor_ref=f'{_CONFIDENCE_MODULE}:RefactorSupportC6DEditor',
        variant_name='source_prompt_source_anchored_support_c6d_dynamic_gap_recovery_v1',
        description='Keeps C6c support-gap recovery but additionally gates it by the live dynamic mask.',
        run_prefix='support_c6d',
        default_output_root='scratch_source_anchor_refactor/support_c6d',
        extra_arg_names=(
            'anchor_relax_start_strength',
            'anchor_relax_end_strength',
            'consistency_floor',
            'roi_trust_max_strength',
            'roi_trust_start_ratio',
            'roi_trust_full_ratio',
        ),
    ),
}


def get_support_variant(key: str) -> SupportVariantSpec:
    try:
        return SUPPORT_VARIANTS[key]
    except KeyError as exc:
        raise KeyError(f'Unknown support variant: {key}') from exc
