name: dymask-refactor
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.5
  - torchvision=0.20
  - pytorch-cuda=12.1
  - numpy=2.2
  - pandas=2.3
  - pyarrow=23.0
  - pillow=12.0
  - scikit-image=0.25
  - pip
  - pip:
      - diffusers==0.37.1
      - transformers==5.4.0
      - safetensors==0.7.0
      - accelerate
      - lpips
      - opencv-python
      - ipython
      - tensorboard
      - tqdm
